# Generated by Django 2.0 on 2018-11-01 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Should have at least a page')], verbose_name='Page Count')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1, "Price can't be less than 1")], verbose_name='Price')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'adventure'), (0, 'horror'), (2, 'fiction'), (3, 'science'), (4, 'biography')], verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_of_birth', models.DateTimeField(verbose_name='DOB')),
            ],
        ),
    ]
